#
# CORL Vagrant environment (development platform)
#-------------------------------------------------------------------------------
#
Vagrant.configure('2') do |config|
  CORL.vagrant_config(File.dirname(__FILE__), config) do |node, machine, provisioner|
    provisioner.provision = false
    #provisioner.dry_run   = true  
  end
end
