# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "corl"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Webb"]
  s.date = "2014-02-20"
  s.description = "= CORL (Cluster Orchestration and Research Library)\n\nComing soon!\n\nNote:  This library is still very early in development!\n\n== Contributing to CORL\n \n* Check out the latest {major}.{minor} branch to make sure the feature hasn't \n  been implemented or the bug hasn't been fixed yet.\n* Check out the issue tracker to make sure someone already hasn't requested \n  it and/or contributed it.\n* Fork the project.\n* Start a feature/bugfix branch.\n* Commit and push until you are happy with your contribution.\n* Make sure to add tests for it. This is important so I don't break it in a \n  future version unintentionally.\n* Please try not to mess with the Rakefile, version, or history. If you want \n  to have your own version, or is otherwise necessary, that is fine, but \n  please isolate to its own commit so I can cherry-pick around it.\n\n== Copyright\n\nLicensed under GPLv3.  See LICENSE.txt for further details.\n\nCopyright (c) 2013  Adrian Webb <adrian.webb@coralnexus.com>\nCoral Technology Group LLC"
  s.email = "adrian.webb@coralnexus.com"
  s.executables = ["corl"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitmodules",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/corl",
    "lib/corl.rb",
    "lib/corl/action/add.rb",
    "lib/corl/action/bootstrap.rb",
    "lib/corl/action/clone.rb",
    "lib/corl/action/create.rb",
    "lib/corl/action/exec.rb",
    "lib/corl/action/extract.rb",
    "lib/corl/action/image.rb",
    "lib/corl/action/images.rb",
    "lib/corl/action/lookup.rb",
    "lib/corl/action/machines.rb",
    "lib/corl/action/provision.rb",
    "lib/corl/action/remove.rb",
    "lib/corl/action/save.rb",
    "lib/corl/action/seed.rb",
    "lib/corl/action/spawn.rb",
    "lib/corl/action/start.rb",
    "lib/corl/action/stop.rb",
    "lib/corl/action/update.rb",
    "lib/corl/command/shell.rb",
    "lib/corl/configuration/file.rb",
    "lib/corl/event/puppet.rb",
    "lib/corl/event/regex.rb",
    "lib/corl/extension/puppetloader.rb",
    "lib/corl/machine/fog.rb",
    "lib/corl/machine/physical.rb",
    "lib/corl/network/default.rb",
    "lib/corl/node/aws.rb",
    "lib/corl/node/fog.rb",
    "lib/corl/node/google.rb",
    "lib/corl/node/local.rb",
    "lib/corl/node/rackspace.rb",
    "lib/corl/project/git.rb",
    "lib/corl/project/github.rb",
    "lib/corl/provisioner/puppetnode.rb",
    "lib/corl/provisioner/puppetnode/resource.rb",
    "lib/corl/provisioner/puppetnode/resource_group.rb",
    "lib/corl/template/environment.rb",
    "lib/corl/template/json.rb",
    "lib/corl/template/wrapper.rb",
    "lib/corl/template/yaml.rb",
    "lib/corl/translator/json.rb",
    "lib/corl/translator/yaml.rb",
    "lib/corl_core/codes.rb",
    "lib/corl_core/config.rb",
    "lib/corl_core/config/collection.rb",
    "lib/corl_core/config/options.rb",
    "lib/corl_core/core.rb",
    "lib/corl_core/corl.rb",
    "lib/corl_core/errors.rb",
    "lib/corl_core/facade.rb",
    "lib/corl_core/gems.rb",
    "lib/corl_core/manager.rb",
    "lib/corl_core/mixin/action/commit.rb",
    "lib/corl_core/mixin/action/keypair.rb",
    "lib/corl_core/mixin/action/node.rb",
    "lib/corl_core/mixin/action/project.rb",
    "lib/corl_core/mixin/action/push.rb",
    "lib/corl_core/mixin/config/collection.rb",
    "lib/corl_core/mixin/config/ops.rb",
    "lib/corl_core/mixin/config/options.rb",
    "lib/corl_core/mixin/lookup.rb",
    "lib/corl_core/mixin/macro/object_interface.rb",
    "lib/corl_core/mixin/macro/plugin_interface.rb",
    "lib/corl_core/mixin/settings.rb",
    "lib/corl_core/mixin/sub_config.rb",
    "lib/corl_core/mod/hash.rb",
    "lib/corl_core/mod/hiera_backend.rb",
    "lib/corl_core/plugin/action.rb",
    "lib/corl_core/plugin/base.rb",
    "lib/corl_core/plugin/command.rb",
    "lib/corl_core/plugin/configuration.rb",
    "lib/corl_core/plugin/event.rb",
    "lib/corl_core/plugin/extension.rb",
    "lib/corl_core/plugin/machine.rb",
    "lib/corl_core/plugin/network.rb",
    "lib/corl_core/plugin/node.rb",
    "lib/corl_core/plugin/project.rb",
    "lib/corl_core/plugin/provisioner.rb",
    "lib/corl_core/plugin/template.rb",
    "lib/corl_core/plugin/translator.rb",
    "lib/corl_core/util/cli.rb",
    "lib/corl_core/util/data.rb",
    "lib/corl_core/util/disk.rb",
    "lib/corl_core/util/git.rb",
    "lib/corl_core/util/interface.rb",
    "lib/corl_core/util/liquid.rb",
    "lib/corl_core/util/package.rb",
    "lib/corl_core/util/shell.rb",
    "lib/corl_core/util/ssh.rb",
    "lib/facter/corl_config_ready.rb",
    "lib/facter/corl_exists.rb",
    "lib/facter/corl_network.rb",
    "lib/hiera/corl_logger.rb",
    "lib/puppet/indirector/corl.rb",
    "lib/puppet/indirector/data_binding/corl.rb",
    "lib/puppet/parser/functions/config_initialized.rb",
    "lib/puppet/parser/functions/corl_include.rb",
    "lib/puppet/parser/functions/corl_resources.rb",
    "lib/puppet/parser/functions/deep_merge.rb",
    "lib/puppet/parser/functions/ensure.rb",
    "lib/puppet/parser/functions/file_exists.rb",
    "lib/puppet/parser/functions/global_array.rb",
    "lib/puppet/parser/functions/global_hash.rb",
    "lib/puppet/parser/functions/global_options.rb",
    "lib/puppet/parser/functions/global_param.rb",
    "lib/puppet/parser/functions/interpolate.rb",
    "lib/puppet/parser/functions/is_false.rb",
    "lib/puppet/parser/functions/is_true.rb",
    "lib/puppet/parser/functions/module_array.rb",
    "lib/puppet/parser/functions/module_hash.rb",
    "lib/puppet/parser/functions/module_options.rb",
    "lib/puppet/parser/functions/module_param.rb",
    "lib/puppet/parser/functions/name.rb",
    "lib/puppet/parser/functions/render.rb",
    "lib/puppet/parser/functions/value.rb",
    "locales/en.yml",
    "spec/corl_core/interface_spec.rb",
    "spec/corl_mock_input.rb",
    "spec/corl_test_kernel.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/coralnexus/corl"
  s.licenses = ["GPLv3"]
  s.rdoc_options = ["--title", "Cluster Orchestration and Research Library", "--main", "README.rdoc", "--line-numbers"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.1")
  s.rubyforge_project = "corl"
  s.rubygems_version = "1.8.11"
  s.summary = "Provides core data elements and utilities used in other CORL gems"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<log4r>, ["~> 1.1"])
      s.add_runtime_dependency(%q<i18n>, ["~> 0.6"])
      s.add_runtime_dependency(%q<deep_merge>, ["~> 1.0"])
      s.add_runtime_dependency(%q<celluloid>, ["~> 0.15"])
      s.add_runtime_dependency(%q<sshkey>, ["~> 1.6"])
      s.add_runtime_dependency(%q<hiera>, ["~> 1.3"])
      s.add_runtime_dependency(%q<multi_json>, ["~> 1.7"])
      s.add_runtime_dependency(%q<grit>, ["~> 2.5"])
      s.add_runtime_dependency(%q<octokit>, ["~> 2.7"])
      s.add_runtime_dependency(%q<netrc>, ["~> 0.7"])
      s.add_runtime_dependency(%q<fog>, ["~> 1.20"])
      s.add_runtime_dependency(%q<rgen>, ["~> 0.6"])
      s.add_runtime_dependency(%q<facter>, ["~> 1.7"])
      s.add_runtime_dependency(%q<puppet>, ["~> 3.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.10"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
    else
      s.add_dependency(%q<log4r>, ["~> 1.1"])
      s.add_dependency(%q<i18n>, ["~> 0.6"])
      s.add_dependency(%q<deep_merge>, ["~> 1.0"])
      s.add_dependency(%q<celluloid>, ["~> 0.15"])
      s.add_dependency(%q<sshkey>, ["~> 1.6"])
      s.add_dependency(%q<hiera>, ["~> 1.3"])
      s.add_dependency(%q<multi_json>, ["~> 1.7"])
      s.add_dependency(%q<grit>, ["~> 2.5"])
      s.add_dependency(%q<octokit>, ["~> 2.7"])
      s.add_dependency(%q<netrc>, ["~> 0.7"])
      s.add_dependency(%q<fog>, ["~> 1.20"])
      s.add_dependency(%q<rgen>, ["~> 0.6"])
      s.add_dependency(%q<facter>, ["~> 1.7"])
      s.add_dependency(%q<puppet>, ["~> 3.2"])
      s.add_dependency(%q<bundler>, ["~> 1.2"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.10"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<log4r>, ["~> 1.1"])
    s.add_dependency(%q<i18n>, ["~> 0.6"])
    s.add_dependency(%q<deep_merge>, ["~> 1.0"])
    s.add_dependency(%q<celluloid>, ["~> 0.15"])
    s.add_dependency(%q<sshkey>, ["~> 1.6"])
    s.add_dependency(%q<hiera>, ["~> 1.3"])
    s.add_dependency(%q<multi_json>, ["~> 1.7"])
    s.add_dependency(%q<grit>, ["~> 2.5"])
    s.add_dependency(%q<octokit>, ["~> 2.7"])
    s.add_dependency(%q<netrc>, ["~> 0.7"])
    s.add_dependency(%q<fog>, ["~> 1.20"])
    s.add_dependency(%q<rgen>, ["~> 0.6"])
    s.add_dependency(%q<facter>, ["~> 1.7"])
    s.add_dependency(%q<puppet>, ["~> 3.2"])
    s.add_dependency(%q<bundler>, ["~> 1.2"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.10"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
  end
end

